### ISSUE TITLE
Linking against system pugixml fails

### ISSUE THREAD

**Issue by PeterKraus** [robashaw/libecpint#39]
Hi Robert,
I'm trying to get my head around libecpint, but I have hit a snag when compiling. I am not sure this is a cmake or libecpint issue:

- the compilation works OK with no system pugixml
- the compilation works OK with Arch Linux `pugixml-1.11.4-1` (header in `/usr/include/pugixml.hpp` and the lib in `/usr/lib/libpugixml.so`) and Arch Linux `cmake-3.19.7-1`
- the compilation works OK with conda-forge's `pugixml-1.10` and conda's `cmake-3.19.6` from default channel
- the compilation **crashes** with Arch Linux `pugixml` and conda's `cmake-3.19.6` from default channel:
```
Scanning dependencies of target ecpint
[  4%] Building CXX object src/CMakeFiles/ecpint.dir/lib/angular.cpp.o
[  4%] Building CXX object src/CMakeFiles/ecpint.dir/lib/api.cpp.o
[  5%] Building CXX object src/CMakeFiles/ecpint.dir/lib/bessel.cpp.o
[  5%] Building CXX object src/CMakeFiles/ecpint.dir/lib/ecp.cpp.o
/home/kraus/Build/libecpint/src/lib/ecp.cpp:30:10: fatal error: pugixml.hpp: No such file or directory
 #include "pugixml.hpp"
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/ecpint.dir/build.make:503: src/CMakeFiles/ecpint.dir/lib/ecp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1523: src/CMakeFiles/ecpint.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```
I am puzzled by this weird interaction, especially as the `${PUGIXML_LIBRARY}` and `${PUGIXML_INCLUDE_DIR}` are populated correctly in all four cases. I suppose it makes sense to use conda packages when compiling with conda cmake, and system packages with system cmake.

**Comment by robashaw** [comment]
I honestly have no idea why this would happen if the ```${PUGIXML_INCLUDE_DIR}``` is correct. I'm also unsure how I would go about even trying to determine what the problem is! If you run make with VERBOSE=1 or similar, does anything seem off?
